<a href="https://colab.research.google.com/github/rosalikas/Belajar-Python/blob/main/Pratice_Pyton_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Contoh Menampilkan Data

In [ ]:
print("Hello World")
print("Selamat malam, Budi")
nama = "BDV"
print("Selamat malam",nama)

Hello World
Selamat malam, Budi
Selamat malam BDV


Menggunakan Operasi Bilangan

In [ ]:
x = 7
y = 5
z = x * y
print("x=", x, "y=", y, "z=", z)

x= 7 y= 5 z= 35


Pengulangan (Looping)

In [ ]:
#tampilan tanpa menggunakan spasi atau tab pada sprint("selamat malam")
print("selamat pagi")
for x in range(10):
  print(x)
print("selamat malam")

selamat pagi
0
1
2
3
4
5
6
7
8
9
selamat malam


In [ ]:
#tampilan dengan menggunakan spasi atau tab pada sprint("selamat malam")
print("selamat pagi")
for x in range(10):
  print(x)
  print("selamat malam")

selamat pagi
0
selamat malam
1
selamat malam
2
selamat malam
3
selamat malam
4
selamat malam
5
selamat malam
6
selamat malam
7
selamat malam
8
selamat malam
9
selamat malam


perhitungan matriks dengan menggunakan numpy

In [ ]:
#import nampy terlebih dahulu
import numpy as np
#masukkan data matrix
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b = np.array([[3,3,3],[2,2,2],[7,7,7]])
print(b)
c = a + b
print(c)
d = a * b
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 3 3]
 [2 2 2]
 [7 7 7]]
[[ 4  5  6]
 [ 6  7  8]
 [14 15 16]]
[[ 3  6  9]
 [ 8 10 12]
 [49 56 63]]
